name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Maven Project
        run: mvn clean package

# configurar depois de atualizar o docker
#      - name: Build Docker Image
 #       run: docker build -t your-docker-image-name:latest .

  #    - name: Login to Docker Hub
   #     run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    #  - name: Push Docker Image
     #   run: docker push your-docker-image-name:latest
